#!/bin/bash
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny75    =
#================================================
#Project:EvolvereMix
#================================================

# Ottiene la cartella dove risiede questo script
DIR_ATTUALE=$(dirname "$(readlink -f "$0")")

set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo -E "$0" "$@"

echo "----------------------------------------------"
echo "Copio il tema delle icone in /usr/share/icons"
echo "----------------------------------------------"
# Usa la variabile DIR_ATTUALE invece del vecchio percorso fisso
cp -a -r "$DIR_ATTUALE" /usr/share/icons/

sleep 2 &&
echo "----------------------------------------------"
echo "      Installo Lila HD Cursor"
echo "----------------------------------------------"
cp -a -r "$DIR_ATTUALE/Lila_HD-cursor/" /usr/share/icons/
rm -r /usr/share/icons/EvolvereMix/Lila_HD-cursor || true
rm -r /usr/share/icons/EvolvereMix/.git || true

echo "----------------------------------------------"
echo "Tema di icone e cursore installato, enjoy :D"
echo "----------------------------------------------"
exit 0
