#!/bin/bash
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny75    =
#================================================
#Project:EvolvereMix
#================================================

# Ottiene la cartella dove risiede questo script (dinamico)
DIR_ATTUALE=$(dirname "$(readlink -f "$0")")

set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo -E "$0" "$@" [cite: 1, 2]

echo "----------------------------------------------"
echo "Copio il tema delle icone in /usr/share/icons"
echo "----------------------------------------------"
# Forza il nome della destinazione a EvolvereMix
cp -a -r "$DIR_ATTUALE" /usr/share/icons/EvolvereMix

sleep 2 &&
echo "----------------------------------------------"
echo "      Installo Lila HD Cursor"
echo "----------------------------------------------"
# Installa il cursore dalla sottocartella corretta
cp -a -r "$DIR_ATTUALE/Lila_HD-cursor/" /usr/share/icons/
rm -rf /usr/share/icons/EvolvereMix/Lila_HD-cursor
rm -rf /usr/share/icons/EvolvereMix/.git

echo "----------------------------------------------"
echo "Tema di icone e cursore installato, enjoy :D"
echo "----------------------------------------------"
exit 0
